<div class="bg-white rounded p-4 shadow relative shadow:md mb-4">
    <h1 class="text-3xl font-semibold">Pengenalan Jaringan</h1>
    <h2 class="text-2xl font-semibold">A. Dasar Teori</h2>
    <h3 class="text-xl font-semibold mt-4">Pengertian</h3>
    <ol class="list-decimal list-inside pl-4">
        <li><strong>Menurut Bahasa:</strong><br>Jaringan komputer adalah sistem yang terdiri dari dua atau lebih perangkat komputer yang terhubung bersama dengan tujuan berbagi sumber daya, seperti data, aplikasi, atau perangkat keras, serta memungkinkan komunikasi antar perangkat tersebut. Dalam jaringan komputer, perangkat-perangkat ini dapat berkomunikasi secara lokal atau melalui jarak jauh, tergantung pada topologi dan teknologi yang digunakan.</li>
    </ol>
    <h3 class="text-xl font-semibold mt-4">Menurut Para Ahli:</h3>
    <ul class="list-disc list-inside pl-4">
        <li><strong>Andrew S. Tanenbaum:</strong><br>Andrew S. Tanenbaum, seorang pakar dalam bidang jaringan komputer, memberikan pengertian jaringan komputer sebagai berikut:<br>"Jaringan komputer adalah kumpulan dari dua atau lebih perangkat komputer yang dihubungkan bersama-sama sehingga dapat berkomunikasi dan berbagi sumber daya, seperti data dan perangkat keras."<br><img src="../materials_data/1_A)DasarTeori/AndrewSTanenbaum.jpg" alt="Andrew S. Tanenbaum" class="w-1/4 mx-auto mt-4"></li>
        <li><strong>Douglas E. Comer:</strong><br>Douglas E. Comer, seorang penulis terkenal dalam bidang jaringan komputer, mendefinisikan jaringan komputer sebagai berikut:<br>"Jaringan komputer adalah infrastruktur yang memungkinkan komunikasi data antara berbagai perangkat komputer dan sistem komunikasi. Tujuannya adalah untuk memfasilitasi pertukaran informasi dan sumber daya antara pengguna."<br><img src="../materials_data/1_A)DasarTeori/DouglasEComer.jpg" alt="Douglas E. Comer" class="w-1/4 mx-auto mt-4"></li>
        <li><strong>Larry L. Peterson dan Bruce S. Davie:</strong><br>Larry L. Peterson dan Bruce S. Davie, dalam buku mereka yang terkenal tentang jaringan komputer, menjelaskan pengertian jaringan komputer sebagai berikut:<br>"Jaringan komputer adalah kumpulan perangkat keras dan perangkat lunak yang bekerja sama untuk menghubungkan komputer-komputer dan perangkat lainnya sehingga pengguna dapat berkomunikasi, berbagi sumber daya, dan mengakses informasi secara efisien."<br><img src="../materials_data/1_A)DasarTeori/LarryLPeterson.jpg" alt="Larry L. Peterson dan Bruce S. Davie" class="w-1/4 mx-auto mt-4"></li>
    </ul>
    <h3 class="text-xl font-semibold mt-4">Sejarah Jaringan Komputer</h3>
    <ul class="list-disc list-inside pl-4">
        <li><strong>1940:</strong><br>Sejarah jaringan computer (Computer Network) dimulai dari lahirnya konsep jaringan komputer pada tahun 1940-an di Amerika yang dibuat oleh proyek untuk pengembangan komputer di laboratorium Bell dan group riset dari Universitas Harvard yang dipimpin profesor Howard Aiken. Pada awalnya penemuan tersebut digunakan untuk memanfaatkan sebuah perangkat komputer untuk keperluan bersama. Idenya adalah untuk mengerjakan beberapa tugas tanpa membuang waktu kosong yang terlalu banyak, maka dibuatlah proses beruntun, sehingga program bisa dijalankan dalam beberapa komputer.</li>
        <li><strong>1950:</strong><br>Pada tahun 1950-an ketika komputer mulai berkembang sampai terciptanya super komputer, maka sebuah komputer harus melayani beberapa tempat yang tersedia (terminal), untuk itu ditemukan konsep distribusi proses berdasarkan waktu yang dikenal dengan nama TSS (Time Sharing System). Maka untuk pertama kalinya bentuk jaringan (network) komputer diaplikasikan. Pada sistem TSS beberapa terminal terhubung secara seri ke sebuah komputer atau perangkat lainnya yang terhubung dalam suatu jaringan (host) komputer.</li>
        <li><strong>1973:</strong><br>Pada Tahun 1973 ke atas dikenal sebagai Kelahiran dari internet atau jaringan internasional (International Network), Terdapat dua orang ahli komputer yang mengembangkan dan juga mengusulkan sebuah jaringan yang bersifat sangat luas dan dapat digunakan oleh semua orang di dunia. Vinton Cerf dan juga Bob Kahn adalah kedua orang tersebut, yang membuat sebuah gagasan besar, yang sebenarnya menjadi sebuah cikal bakal dari terciptanya internet atau international network. Saat ini, internet pun sudah menjelma menjadi jaringan terbesar yang ada di dunia, dan dapat menghubungkan setiap orang di berbagai belahan dunia.</li>
    </ul>

    <h3 class="text-xl font-semibold mt-4">Fungsi</h3>
    <ul class="list-disc list-inside pl-4">
        <li><strong>Mudah Melakukan Pertukaran Data:</strong><br>Keberadaan jaringan komputer seperti internet dan lain-lain, bisa memudahkan kita untuk melakukan pertukaran data atau dokumen lainnya. Kamu bahkan bisa mengirim dan menerima data melalui berbagai perangkat kapan saja menggunakan internet.</li>
        <li><strong>Menjaga Keamanan Data:</strong><br>Jaringan komputer juga memiliki proteksi atau perlindungan data. Jadi, data atau dokumen penting lainnya yang kamu miliki atau milik perusahaan dapat tersimpan di komputer dengan aman dan terjamin keamanannya. Fungsi jaringan komputer jadi pelindung data yang berguna, termasuk mencegah kehilangan data penting, contohnya data penting perusahaan.</li>
        <li><strong>Memudahkan Komunikasi:</strong><br>Selain mudah untuk pertukaran data, fungsi jaringan komputer juga bisa memudahkan dalam komunikasi jarak jauh sekalipun secara optimal.</li>
        <li><strong>Menyampaikan Informasi Secara Cepat:</strong><br>Saat ini, kamu mungkin dengan mudah memperoleh informasi dari berbagai sumber karena adanya jaringan komputer. Selain itu, kamu juga bisa mengaksesnya kapan saja dan di mana saja tanpa ada batasan jarak dan waktu.</li>
        <li><strong>Menghemat Biaya:</strong><br>Adanya jaringan komputer membuat pengguna tidak perlu repot-repot mencetak dokumen atau file tertentu. Kamu hanya perlu menyimpannya ke dalam perangkat dan bisa dengan mudah mengirim data lewat internet. Jadi tidak perlu biaya untuk mencetak berkas dan lain-lain.</li>
        <li><strong>Tetap Up-to-date:</strong><br>Fungsi penting jaringan komputer juga bisa membuat informasi yang diterima selalu up-to-date. Dengan jaringan komputer bisa mengakses kapan saja. Proses pengiriman informasi juga mudah dan cepat, jadi tidak perlu waktu yang lama.</li>
        <li><strong>Membagi Sumber Daya:</strong><br>Sumber daya ini bisa berupa printer atau sumber daya lain, seperti data-data, software. Sebelum adanya jaringan komputer, printer digunakan hanya untuk satu komputer saja. Namun setelah ada jaringan komputer, jadi bisa digunakan oleh berbagai komputer.</li>
        <li><strong>Reliabilitas Tinggi:</strong><br>Seperti yang disebutkan sebelumnya bahwa fungsi jaringan komputer memungkinkan untuk mengkopi data-data ke lebih dari satu perangkat. Jika ada satu komputer rusak meskipun data-datanya hilang, tetapi data-datanya masih tersimpan di memory komputer lainnya.</li>
        <li><strong>Mempercepat Transfer Data:</strong><br>Proses berbagi data jadi cepat karena transfer data pada jaringan selalu lebih cepat dibandingkan sarana berbagai data lainnya yang bukan jaringan. Hal ini juga sangat mempermudah user dalam memperoleh informasi.</li>
    </ul>

    <h3 class="text-xl font-semibold mt-4">Tujuan</h3>
    <ol class="list-decimal list-inside pl-4">
        <li><strong>Berbagi Sumber Daya:</strong> Jaringan memungkinkan perangkat untuk berbagi peralatan seperti printer, file, dan perangkat keras lainnya.</li>
        <li><strong>Kemampuan Komunikasi:</strong> Memungkinkan pengguna untuk berkomunikasi melalui email, pesan instan, video konferensi, dan lainnya.</li>
        <li><strong>Akses Internet:</strong> Jaringan menyediakan akses ke Internet, yang memungkinkan akses ke sumber daya global dan informasi.</li>
        <li><strong>Peningkatan Keamanan:</strong> Jaringan dapat digunakan untuk mengimplementasikan langkah-langkah keamanan seperti firewall, enkripsi, dan akses terbatas.</li>
        <li><strong>Skalabilitas:</strong> Jaringan dapat diperluas sesuai kebutuhan dengan menambahkan lebih banyak perangkat dan sumber daya.</li>
    </ol>
</div>